# Generated by Django 3.1.12 on 2021-09-26 02:47
import django
from django.conf import settings
from django.db import migrations, models, transaction


def update_users(apps, schema_editor):
    login_acl_model = apps.get_model("acls", "LoginACL")

    updates = list()
    with transaction.atomic():
        for instance in login_acl_model.objects.all():
            instance.users.update({"username_group": ["*"]})
            updates.append(instance)
        login_acl_model.objects.bulk_update(updates, ['users', ])


def migrate_login_confirm(apps, schema_editor):
    login_acl_model = apps.get_model("acls", "LoginACL")
    login_confirm_model = apps.get_model("authentication", "LoginConfirmSetting")

    with transaction.atomic():
        for instance in login_confirm_model.objects.filter(is_active=True):
            user = instance.user
            reviewers = instance.reviewers.all()
            if reviewers.count() == 0:
                continue
            data = {
                'name': '{0}-login-confirm'.format(user.username),
                'user': user,
                'created_by': instance.created_by,
                'is_login_confirm': True,
                'action': 'allow',
                'ip_group': ["*"],
                'users': {"username_group": []},
            }
            instance = login_acl_model.objects.create(**data)
            instance.reviewers.set(reviewers)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginacl',
            name='is_login_confirm',
            field=models.BooleanField(default=False, verbose_name='Is login confirm'),
        ),
        migrations.AddField(
            model_name='loginacl',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='review_login_confirm_login_acls',
                                         to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='loginacl',
            name='users',
            field=models.JSONField(default=dict, verbose_name='User match'),
        ),
        migrations.AlterField(
            model_name='loginacl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_acls', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RunPython(update_users),
        migrations.RunPython(migrate_login_confirm),
    ]
